// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3352.FlamingMonkeys2015.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3352.FlamingMonkeys2015.Robot;
import edu.wpi.first.wpilibj.smartdashboard.*;

/**
 *
 */
public class  LiftToPosition extends Command {
	int current;
	int target;
    public LiftToPosition() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.lift);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	target=Robot.oi.getTargetLevel();
    	current=Robot.lift.getLevel();
    	SmartDashboard.putNumber("target", target);
    	SmartDashboard.putNumber("current", current);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	current=lastLevel();
		target=lastTarget();
		SmartDashboard.putNumber("target", target);
    	SmartDashboard.putNumber("current", current);
    	if(target>current){
    		Robot.lift.liftUp();
        	SmartDashboard.putString("liftDirection", "up");
    	}else if(target<current){
    		Robot.lift.liftDown();
        	SmartDashboard.putString("liftDirection", "down");
    	}
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	return current==target;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.lift.liftOff();
    	SmartDashboard.putString("liftDirection", "off");
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
    
    private int lastLevel(){
    	int l=0;
    	if(Robot.lift.getLevel()>0){
    		l = Robot.lift.getLevel();
    	}
    	return l;
    }
    
    private int lastTarget(){
    	int t=0;
    	if(Robot.oi.getTargetLevel()>0){
    		t = Robot.oi.getTargetLevel();
    	}
    	return t;
    }
    
}
